# Generated by Django 5.1.6 on 2025-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='temp_user_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
